# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      # - id: no-commit-to-branch
      #   args: ["--branch", "main"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        # Run the formatter.
      - id: ruff-format
  # keep lockfile synced with pyproject.toml
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.15
    hooks:
      - id: uv-lock
