# Read the Docs configuration file for Groundhog
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      # Install dependencies using uv
      - pip install uv
      - uv sync --all-groups

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
