# Read the Docs configuration file for Groundhog
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv sync --group docs
    - uv run typer groundhog_hpc.app.main utils docs --title "Groundhog CLI Reference" --name hog --output docs/api/cli.md
    - uv run mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
